name: traj
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy
  - notebook
  - ipykernel
  - ca-certificates
  - certifi
  - openssl
  - scikit-learn
  - biopython
  - scanpy
  - scipy
  - pip:
    - palantir
    - pyslingshot
    - gif
    - mycolorpy
    - louvain
    - openpyxl
